# Generated by Django 4.2.1 on 2023-07-25 06:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Status')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Upatded Datetime')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
