# Generated by Django 4.2.1 on 2023-07-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(db_index=True, max_length=15, verbose_name='Item')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Name')),
                ('body', models.TextField(blank=True, db_index=True, null=True, verbose_name='Body')),
                ('like_count', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Like Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
